import React, { useState, useEffect } from "react";
import { motion, AnimatePresence } from "motion/react";
import { Sparkles, HelpCircle, AlertCircle, Plus, Check, Scissors, Palette, DraftingCompass } from "lucide-react";
import { StyleArchetype, WardrobeItem, ColorPalette } from "../types";

interface AtelierProps {
  selectedArchetype: StyleArchetype;
  onAddItem: (item: WardrobeItem) => void;
  setActiveTab: (tab: string) => void;
}

interface DesignOutput {
  name: string;
  narrative: string;
  fabrics: string[];
  colorPalette: ColorPalette[];
  technicalSpecs: string[];
  imagePrompt: string;
}

export default function Atelier({
  selectedArchetype,
  onAddItem,
  setActiveTab,
}: AtelierProps) {
  const [prompt, setPrompt] = useState("");
  const [archetype, setArchetype] = useState<StyleArchetype>(selectedArchetype);
  const [structure, setStructure] = useState("Balanced Fluidity");
  const [vibe, setVibe] = useState("Modern Elegance");
  const [type, setType] = useState<WardrobeItem["type"]>("Outerwear");

  // Loading & Progress simulation states
  const [loading, setLoading] = useState(false);
  const [loadingStep, setLoadingStep] = useState(0);
  const [error, setError] = useState<string | null>(null);

  // Result states
  const [result, setResult] = useState<DesignOutput | null>(null);
  const [sketchUrl, setSketchUrl] = useState<string | null>(null);
  const [isAdded, setIsAdded] = useState(false);

  // Sync preselected archetype from dashboard
  useEffect(() => {
    setArchetype(selectedArchetype);
  }, [selectedArchetype]);

  // Loading text sequence
  const loadingTexts = [
    "Spinning structural carbon-linen filaments...",
    "Drafting pattern coordinates on digital mannequin...",
    "Simulating drape fluid tension vectors...",
    "Interweaving high-fashion editorial metadata...",
    "Rendering custom bespoke vector visual sketch..."
  ];

  useEffect(() => {
    let interval: NodeJS.Timeout;
    if (loading) {
      interval = setInterval(() => {
        setLoadingStep((prev) => (prev < loadingTexts.length - 1 ? prev + 1 : prev));
      }, 2500);
    } else {
      setLoadingStep(0);
    }
    return () => clearInterval(interval);
  }, [loading]);

  const handleDesignDraft = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!prompt.trim()) return;

    setLoading(true);
    setError(null);
    setResult(null);
    setSketchUrl(null);
    setIsAdded(false);

    try {
      const response = await fetch("/api/design", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          prompt,
          archetype,
          structure,
          vibe,
        }),
      });

      const data = await response.json();

      if (!response.ok || data.error) {
        throw new Error(data.error || "An error occurred during garment draping.");
      }

      setResult(data.design);
      setSketchUrl(data.sketchUrl);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to drape garment. Check connection or API keys.");
    } finally {
      setLoading(false);
    }
  };

  const handleAddToWardrobe = () => {
    if (!result) return;

    const newItem: WardrobeItem = {
      id: `custom-${Date.now()}`,
      name: result.name,
      narrative: result.narrative,
      fabrics: result.fabrics,
      colors: result.colorPalette,
      technicalSpecs: result.technicalSpecs,
      // If sketchUrl is generated by Gemini 2.5-flash-image, use it!
      // Otherwise, fallback to a elegant placeholder illustration
      imageUrl: sketchUrl || "https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=600&auto=format&fit=crop",
      type: type,
      archetype: archetype,
      isCustom: true,
      createdAt: new Date().toISOString()
    };

    onAddItem(newItem);
    setIsAdded(true);
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
      {/* Configuration Column */}
      <div className="lg:col-span-5 space-y-6">
        <div className="space-y-1">
          <h2 className="text-2xl font-light text-white tracking-tight flex items-center gap-2">
            <Scissors className="w-5 h-5 text-[#C5A367]" /> AI Atelier
          </h2>
          <p className="text-xs text-[#8E9299] font-light">Describe your ideal piece and let the tailor compile it.</p>
        </div>

        <form onSubmit={handleDesignDraft} className="space-y-5 bg-[#0D0D0D] border border-white/5 p-6 rounded-sm">
          {/* Prompt description */}
          <div className="space-y-2">
            <label id="lbl-prompt" className="block text-xs font-mono uppercase text-[#8E9299] tracking-widest">
              Garment Directive
            </label>
            <textarea
              id="txt-prompt"
              rows={4}
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              placeholder="e.g. A charcoal double-breasted wrap blazer featuring an oversized asymmetric lapel, styled in heavy structured wool with memory creases."
              className="w-full text-sm p-4 border border-white/10 rounded-sm focus:border-[#C5A367] focus:outline-none font-sans font-light placeholder:text-neutral-600 resize-none bg-[#141414] text-white"
              required
            />
          </div>

          {/* Type Selection */}
          <div className="space-y-2">
            <label className="block text-xs font-mono uppercase text-[#8E9299] tracking-widest">Garment Category</label>
            <div className="grid grid-cols-3 gap-2">
              {["Top", "Bottom", "Outerwear", "Dress", "Accessory"].map((cat) => (
                <button
                  key={cat}
                  type="button"
                  onClick={() => setType(cat as WardrobeItem["type"])}
                  className={`px-3 py-2 border rounded-sm text-xs font-light transition-all cursor-pointer ${
                    type === cat
                      ? "border-[#C5A367] bg-[#C5A367]/10 text-[#C5A367]"
                      : "border-white/5 hover:border-white/20 bg-[#141414] text-[#8E9299]"
                  }`}
                >
                  {cat}
                </button>
              ))}
            </div>
          </div>

          {/* Archetype Override */}
          <div className="space-y-2">
            <label className="block text-xs font-mono uppercase text-[#8E9299] tracking-widest">Styling Persona</label>
            <select
              value={archetype}
              onChange={(e) => setArchetype(e.target.value as StyleArchetype)}
              className="w-full p-3 border border-white/10 rounded-sm text-xs font-light focus:border-[#C5A367] focus:outline-none bg-[#141414] text-white"
            >
              {["Minimalist", "Avant-Garde", "Structured Tailoring", "Romantic Draper", "Cyberpunk Tailor"].map((arch) => (
                <option key={arch} value={arch} className="bg-[#141414] text-white">
                  {arch} Style
                </option>
              ))}
            </select>
          </div>

          {/* Silhouette Spec sliders */}
          <div className="space-y-3 pt-2">
            <label className="block text-xs font-mono uppercase text-[#8E9299] tracking-widest">Silhouette & Tailor Metric</label>
            
            <div className="space-y-1.5">
              <div className="flex justify-between text-[11px] font-mono text-[#8E9299]">
                <span>Drape Tension</span>
                <span className="text-[#C5A367] font-medium">{structure}</span>
              </div>
              <div className="grid grid-cols-3 gap-2">
                {["Pure Fluidity", "Balanced Fluidity", "Structured Shell"].map((st) => (
                  <button
                    key={st}
                    type="button"
                    onClick={() => setStructure(st)}
                    className={`py-1.5 border rounded-sm text-[10px] cursor-pointer transition-colors ${
                      structure === st
                        ? "border-[#C5A367] bg-[#C5A367]/10 text-[#C5A367]"
                        : "border-white/5 hover:border-white/20 bg-[#141414] text-[#8E9299]"
                    }`}
                  >
                    {st}
                  </button>
                ))}
              </div>
            </div>

            <div className="space-y-1.5 pt-1">
              <div className="flex justify-between text-[11px] font-mono text-[#8E9299]">
                <span>Artistic Finishing</span>
                <span className="text-[#C5A367] font-medium">{vibe}</span>
              </div>
              <div className="grid grid-cols-3 gap-2">
                {["Classic Modern", "Modern Elegance", "Extreme Concept"].map((vb) => (
                  <button
                    key={vb}
                    type="button"
                    onClick={() => setVibe(vb)}
                    className={`py-1.5 border rounded-sm text-[10px] cursor-pointer transition-colors ${
                      vibe === vb
                        ? "border-[#C5A367] bg-[#C5A367]/10 text-[#C5A367]"
                        : "border-white/5 hover:border-white/20 bg-[#141414] text-[#8E9299]"
                    }`}
                  >
                    {vb}
                  </button>
                ))}
              </div>
            </div>
          </div>

          {/* Drape action */}
          <button
            id="btn-drape-draft"
            type="submit"
            disabled={loading}
            className={`w-full py-3.5 rounded-sm font-semibold text-xs tracking-widest uppercase transition-colors cursor-pointer ${
              loading
                ? "bg-white/5 text-neutral-500 border border-white/5 cursor-not-allowed"
                : "bg-[#C5A367] hover:bg-[#b08e54] text-neutral-950"
            }`}
          >
            {loading ? "Tailoring Design..." : "Drape Bespoke Design"}
          </button>
        </form>
      </div>

      {/* Showcase / Canvas Result Column */}
      <div className="lg:col-span-7 flex flex-col min-h-[450px]">
        <AnimatePresence mode="wait">
          {/* Default / Unloaded Atelier Sandbox Screen */}
          {!loading && !result && !error && (
            <motion.div
              key="sandbox-empty"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="flex-1 flex flex-col items-center justify-center border border-dashed border-white/10 rounded-sm bg-[#0D0D0D] p-8 text-center space-y-4"
            >
              <div className="p-4 bg-[#141414] rounded-sm text-[#8E9299]">
                <DraftingCompass className="w-8 h-8" />
              </div>
              <div className="space-y-1 max-w-sm">
                <h3 className="text-base font-medium text-white">Drafting Canvas Empty</h3>
                <p className="text-xs text-[#8E9299] font-light leading-relaxed">
                  Enter your creative directive in the atelier console. Our AI designer will drape, write, and illustrate a unique sartorial concept.
                </p>
              </div>
            </motion.div>
          )}

          {/* Loading Screen */}
          {loading && (
            <motion.div
              key="sandbox-loading"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="flex-1 flex flex-col items-center justify-center border border-white/5 bg-[#0D0D0D] rounded-sm p-8 text-center space-y-6"
            >
              <div className="relative">
                {/* Custom Elegant spinning/pulsing dress form simulation */}
                <div className="w-16 h-16 border border-white/5 border-t-[#C5A367] rounded-full animate-spin" />
                <Scissors className="w-5 h-5 text-[#8E9299] absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2" />
              </div>
              <div className="space-y-2">
                <h3 className="text-sm font-medium text-white tracking-tight">Draping Bespoke Silhouette</h3>
                {/* Stepped loader text */}
                <p className="text-xs text-[#C5A367] font-mono animate-pulse min-h-[16px]">
                  {loadingTexts[loadingStep]}
                </p>
              </div>
            </motion.div>
          )}

          {/* Error Message Screen */}
          {error && (
            <motion.div
              key="sandbox-error"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="flex-1 flex flex-col items-center justify-center border border-red-950/40 bg-red-950/10 rounded-sm p-8 text-center space-y-4"
            >
              <div className="p-3 bg-red-950/20 text-red-400 rounded-sm">
                <AlertCircle className="w-6 h-6" />
              </div>
              <div className="space-y-1 max-w-md">
                <h3 className="text-sm font-medium text-red-100">Drafting Exception</h3>
                <p className="text-xs text-red-400 font-light leading-relaxed">{error}</p>
              </div>
              <button
                type="button"
                onClick={() => setError(null)}
                className="px-4 py-2 border border-white/10 hover:border-[#C5A367] rounded-sm text-xs font-light text-[#8E9299] hover:text-white transition-colors cursor-pointer"
              >
                Reset Canvas
              </button>
            </motion.div>
          )}

          {/* Result Showcase Card */}
          {result && (
            <motion.div
              key="sandbox-result"
              initial={{ opacity: 0, scale: 0.98 }}
              animate={{ opacity: 1, scale: 1 }}
              className="flex-1 grid grid-cols-1 md:grid-cols-12 gap-6 bg-[#0D0D0D] border border-white/10 rounded-sm p-6 shadow-sm"
            >
              {/* Illustrated sketch */}
              <div className="md:col-span-5 flex flex-col space-y-3">
                <div className="relative aspect-[3/4] w-full bg-[#141414] border border-white/5 rounded-sm overflow-hidden flex items-center justify-center">
                  {sketchUrl ? (
                    <img
                      src={sketchUrl}
                      alt={result.name}
                      referrerPolicy="no-referrer"
                      className="w-full h-full object-cover"
                    />
                  ) : (
                    <div className="p-6 text-center space-y-2">
                      <Palette className="w-8 h-8 mx-auto text-[#8E9299]" />
                      <p className="text-[10px] font-mono text-[#8E9299]">Sketch generation fell back to studio default. (Paid key check skipped)</p>
                      <img
                        src="https://images.unsplash.com/photo-1539109136881-3be0616acf4b?q=80&w=400&auto=format&fit=crop"
                        alt="Fallback Sketch"
                        className="w-full h-full object-cover absolute inset-0 opacity-20 mix-blend-multiply pointer-events-none"
                      />
                    </div>
                  )}
                  <div className="absolute top-3 left-3 px-2 py-0.5 rounded-sm bg-[#050505] text-[9px] font-mono text-[#C5A367] border border-white/10">
                    Bespoke Sketch
                  </div>
                </div>
                <p className="text-[10px] font-mono text-[#8E9299] leading-relaxed text-center italic">
                  &ldquo;A bespoke design synthesized live using multi-layer text-to-image AI.&rdquo;
                </p>
              </div>

              {/* Design breakdown metadata */}
              <div className="md:col-span-7 space-y-5 flex flex-col justify-between">
                <div className="space-y-4">
                  <div className="space-y-1">
                    <span className="text-[9px] font-mono tracking-widest uppercase text-[#C5A367]">
                      {archetype} &bull; {type}
                    </span>
                    <h3 className="text-xl md:text-2xl font-light text-white tracking-tight leading-tight">
                      {result.name}
                    </h3>
                  </div>

                  <p className="text-xs text-[#8E9299] font-light leading-relaxed italic">
                    &ldquo;{result.narrative}&rdquo;
                  </p>

                  {/* Fabrics */}
                  <div className="space-y-1.5">
                    <h4 className="text-[10px] font-mono uppercase text-[#8E9299] tracking-widest">Textile Blend Matrix</h4>
                    <div className="flex flex-wrap gap-1.5">
                      {result.fabrics.map((fab, i) => (
                        <span key={i} className="text-xs px-2.5 py-1 rounded-sm bg-[#141414] border border-white/5 text-[#E0E0E0]">
                          {fab}
                        </span>
                      ))}
                    </div>
                  </div>

                  {/* Color palette */}
                  <div className="space-y-1.5">
                    <h4 className="text-[10px] font-mono uppercase text-[#8E9299] tracking-widest">Curated Seasonal Palette</h4>
                    <div className="flex gap-4">
                      {result.colorPalette.map((col, i) => (
                        <div key={i} className="flex items-center gap-2">
                          <div
                            className="w-5 h-5 rounded-full border border-white/20"
                            style={{ backgroundColor: col.hex }}
                          />
                          <div className="leading-none">
                            <p className="text-[11px] font-medium text-white">{col.name}</p>
                            <p className="text-[9px] font-mono text-[#8E9299] uppercase">{col.hex}</p>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>

                  {/* Tech specs */}
                  <div className="space-y-1.5">
                    <h4 className="text-[10px] font-mono uppercase text-[#8E9299] tracking-widest">Sartorial Engineering Specs</h4>
                    <ul className="space-y-1">
                      {result.technicalSpecs.map((spec, i) => (
                        <li key={i} className="text-xs font-light text-[#8E9299] flex items-start gap-2">
                          <span className="text-[#C5A367] font-mono">&bull;</span>
                          <span>{spec}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>

                {/* Catalog action */}
                <div className="pt-4 border-t border-white/5 flex items-center justify-between">
                  <div className="text-[10px] text-[#8E9299] font-mono uppercase tracking-wider">
                    Ready for catalog compilation
                  </div>
                  <button
                    id="btn-add-closet"
                    onClick={handleAddToWardrobe}
                    disabled={isAdded}
                    className={`px-4 py-2.5 rounded-sm font-semibold text-xs flex items-center gap-2 transition-all cursor-pointer ${
                      isAdded
                        ? "bg-emerald-950/20 text-emerald-400 border border-emerald-900/50"
                        : "bg-[#C5A367] hover:bg-[#b08e54] text-neutral-950"
                    }`}
                  >
                    {isAdded ? (
                      <>
                        <Check className="w-3.5 h-3.5" /> Added to Wardrobe
                      </>
                    ) : (
                      <>
                        <Plus className="w-3.5 h-3.5" /> Catalog in Wardrobe
                      </>
                    )}
                  </button>
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}
